---
title: '`Course Project` Statistical Inference'
author: '`r if(knitr::is_html_output()) {"&#x1f468;&#x1F3FB;&#x200d;&#x1f4bb; Anderson H Uyekita"} else {NULL}`'
output:
  github_document: default
params:
  author: "Anderson H Uyekita"
  course: 'Statistical Inference'
  course_url: 'https://www.coursera.org/learn/statistical-inference'
  specialization: 'Data Science: Statistics and Machine Learning Specialization'
  specialization_url: 'https://www.coursera.org/specializations/data-science-statistics-machine-learning'
  instructor: "Brian Caffo"
  course_start: !r lubridate::ymd("2022/07/01", tz = "America/Sao_Paulo")
  course_finish: !r lubridate::today(tzone = "America/Sao_Paulo")
  week: "Week 4"
  slug: 'Week%204'
  rpubs: 'https://rpubs.com/AndersonUyekita/course-project_statistical-inference'
  project_repo: 'https://github.com/AndersonUyekita/statistical-inference_course-project'
  codebook: 'https://github.com/AndersonUyekita/statistical-inference_course-project/blob/master/codebook.md'
  instructions: 'https://github.com/AndersonUyekita/statistical-inference_course-project/blob/master/instructions.md'
always_allow_html: true
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(echo=TRUE,cache=TRUE,message=FALSE,warning=FALSE)
library(rmarkdown)
```

`r if(!knitr::is_html_output()) {sprintf(fmt = "* &#x1f468;&#x1F3FB;&#x200d;&#x1f4bb; Author: %s", params$author)}`
`r sprintf(fmt = "* &#x1f4da; Specialization: [%s](%s){target='_blank' rel='noopener'}", params$specialization, params$specialization_url)`
`r sprintf(fmt = "* &#x1f4d6; Course: [%s](%s){target='_blank' rel='noopener'}", params$course, params$course_url)`
    `r sprintf(fmt = "* &#x1F9D1;&#x200d;&#x1F3EB; Instructor: %s", params$instructor)`
`r sprintf(fmt = "* &#x1F4C6; %s", params$week)`
    `r sprintf(fmt = "* &#x1F6A6; Start: %s", format(params$course_start, "%A, %d %B %Y"))`
    `r sprintf(fmt = "* &#x1F3C1; Finish: %s", format(params$course_finish, "%A, %d %B %Y"))`
`r if(!knitr::is_html_output()) {sprintf(fmt = "* &#x1F30E; Rpubs: [Interactive Document](%s)", params$rpubs)}else{sprintf(fmt = "* &#x1F4E6; Github Repository: [Static Document](%s){target='_blank' rel='noopener'}", params$project_repo)}`
`r if(!knitr::is_html_output()) {sprintf(fmt = "* &#x1F4CB; Instructions: [Project Instructions](%s)", "./instructions.md")}else{sprintf(fmt = "* &#x1F4CB; Instructions: [Project Instructions](%s){target='_blank' rel='noopener'}", params$instructions)}`
`r if(!knitr::is_html_output()) {sprintf(fmt = "* &#x1F4C4; README: [README.md](%s)", "./README.md")}else{sprintf(fmt = "* &#x1F4C4; README: [README.md](%s){target='_blank' rel='noopener'}", params$project_repo)}`

--------------------------------------------------------------------------------

## Codebook


Part 1

Part 2