---
title: '`Course Project` Statistical Inference'
author: '`r if(knitr::is_html_output()) {"&#x1f468;&#x1F3FB;&#x200d;&#x1f4bb; Anderson H Uyekita"} else {NULL}`'
output:
  github_document: default
params:
  author: "Anderson H Uyekita"
  course: 'Statistical Inference'
  course_url: 'https://www.coursera.org/learn/statistical-inference'
  specialization: 'Data Science: Statistics and Machine Learning Specialization'
  specialization_url: 'https://www.coursera.org/specializations/data-science-statistics-machine-learning'
  instructor: "Brian Caffo"
  course_start: !r lubridate::ymd("2022/07/01", tz = "America/Sao_Paulo")
  course_finish: !r lubridate::today(tzone = "America/Sao_Paulo")
  week: "Week 4"
  slug: 'Week%204'
  rpubs: 'https://rpubs.com/AndersonUyekita/course-project_statistical-inference'
  project_repo: 'https://github.com/AndersonUyekita/statistical-inference_course-project'
  codebook: 'https://github.com/AndersonUyekita/statistical-inference_course-project/blob/master/codebook.md'
  instructions: 'https://github.com/AndersonUyekita/statistical-inference_course-project/blob/master/instructions.md'
always_allow_html: true
---

```{r setup, include=FALSE,message=FALSE,warning=FALSE,cache=TRUE}
# Defining document chunks options
knitr::opts_chunk$set(echo = TRUE,cache=TRUE,message=FALSE,warning=FALSE)

# Loading required libraries
library(rmarkdown)
library(lubridate)
library(ggplot2)
```

`r if(!knitr::is_html_output()) {sprintf(fmt = "* &#x1f468;&#x1F3FB;&#x200d;&#x1f4bb; Author: %s", params$author)}`
`r sprintf(fmt = "* &#x1f4da; Specialization: [%s](%s){target='_blank' rel='noopener'}", params$specialization, params$specialization_url)`
`r sprintf(fmt = "* &#x1f4d6; Course: [%s](%s){target='_blank' rel='noopener'}", params$course, params$course_url)`
    `r sprintf(fmt = "* &#x1F9D1;&#x200d;&#x1F3EB; Instructor: %s", params$instructor)`
`r sprintf(fmt = "* &#x1F4C6; %s", params$week)`
    `r sprintf(fmt = "* &#x1F6A6; Start: %s", format(params$course_start, "%A, %d %B %Y"))`
    `r sprintf(fmt = "* &#x1F3C1; Finish: %s", format(params$course_finish, "%A, %d %B %Y"))`
`r if(!knitr::is_html_output()) {sprintf(fmt = "* &#x1F4C4; README: [README.md](%s)", "./README.md")}else{sprintf(fmt = "* &#x1F4C4; README: [README.md](%s){target='_blank' rel='noopener'}", params$project_repo)}`
`r if(!knitr::is_html_output()) {sprintf(fmt = "* &#x1F30E; Rpubs: [Interactive Document](%s)", params$rpubs)}else{sprintf(fmt = "* &#x1F4E6; Github Repository: [Static Document](%s){target='_blank' rel='noopener'}", params$project_repo)}`

------------------------------------------------------------------------

## Instructions

### 1. Introduction

The project consists of two parts:

* A simulation exercise.
* Basic inferential data analysis.

You will create a report to answer the questions. Given the nature of the series, ideally you'll use knitr to create the reports and convert to a pdf. (I will post a very simple introduction to knitr). However, feel free to use whatever software that you would like to create your pdf.

Each pdf report should be no more than 3 pages with 3 pages of supporting appendix material if needed (code, figures, etcetera).

### 2. Part 1: Simulation Exercise Instructions

In this project you will investigate the exponential distribution in R and compare it with the **Central Limit Theorem**. The exponential distribution can be simulated in R with `rexp(n, lambda)` where lambda is the rate parameter. The mean of exponential distribution is 1/lambda and the standard deviation is also 1/lambda. Set lambda = 0.2 for all of the simulations. You will investigate the distribution of averages of 40 exponentials. Note that you will need to do a thousand simulations.

Illustrate via simulation and associated explanatory text the properties of the distribution of the mean of 40 exponentials. You should

1. Show the sample mean and compare it to the theoretical mean of the distribution.
2. Show how variable the sample is (via variance) and compare it to the theoretical variance of the distribution.
3. Show that the distribution is approximately normal.

In point 3, focus on the difference between the distribution of a large collection of random exponentials and the distribution of a large collection of averages of 40 exponentials.

As a motivating example, compare the distribution of 1000 random uniforms

```r
hist(runif(1000))
```

and the distribution of 1000 averages of 40 random uniforms

```r
mns = NULL
for (i in 1 : 1000) mns = c(mns, mean(runif(40)))
hist(mns)
```

This distribution looks far more Gaussian than the original uniform distribution!

This exercise is asking you to use your knowledge of the theory given in class to relate the two distributions.

Confused? Try re-watching video lecture 07 for a starter on how to complete this project.

#### 2.1. Sample Project Report Structure

Of course, there are multiple ways one could structure a report to address the requirements above. However, the more clearly you pose and answer each question, the easier it will be for reviewers to clearly identify and evaluate your work.

A sample set of headings that could be used to guide the creation of your report might be:

* Title (give an appropriate title) and Author Name
* Overview: In a few (2-3) sentences explain what is going to be reported on.
* Simulations: Include English explanations of the simulations you ran, with the accompanying R code. Your explanations should make clear what the R code accomplishes.
* Sample Mean versus Theoretical Mean: Include figures with titles. In the figures, highlight the means you are comparing. Include text that explains the figures and what is shown on them, and provides appropriate numbers.
* Sample Variance versus Theoretical Variance: Include figures (output from R) with titles. Highlight the variances you are comparing. * Include text that explains your understanding of the differences of the variances.
* Distribution: Via figures and text, explain how one can tell the distribution is approximately normal.

### 3. Part 2: Basic Inferential Data Analysis Instructions

Now in the second portion of the project, we're going to analyze the ToothGrowth data in the R datasets package.

* Load the ToothGrowth data and perform some basic exploratory data analyses
* Provide a basic summary of the data.
* Use confidence intervals and/or hypothesis tests to compare tooth growth by supp and dose. (Only use the techniques from class, even if there's other approaches worth considering)
* State your conclusions and the assumptions needed for your conclusions.

### 4. Review Criteria

 * Did you show where the distribution is centered at and compare it to the theoretical center of the distribution?
 * Did you show how variable it is and compare it to the theoretical variance of the distribution?
 * Did you perform an exploratory data analysis of at least a single plot or table highlighting basic features of the data?
 * Did the student perform some relevant confidence intervals and/or tests?
 * Were the results of the tests and/or intervals interpreted in the context of the problem correctly?
 * Did the student describe the assumptions needed for their conclusions?