---
title: '`Course Project` Statistical Inference'
author: '`r if(knitr::is_html_output()) {"&#x1f468;&#x1F3FB;&#x200d;&#x1f4bb; Anderson H Uyekita"} else {NULL}`'
output:
  github_document: default
params:
  author: "Anderson H Uyekita"
  course: 'Statistical Inference'
  course_url: 'https://www.coursera.org/learn/statistical-inference'
  specialization: 'Data Science: Statistics and Machine Learning Specialization'
  specialization_url: 'https://www.coursera.org/specializations/data-science-statistics-machine-learning'
  instructor: "Brian Caffo"
  course_start: !r lubridate::ymd("2022/07/01", tz = "America/Sao_Paulo")
  course_finish: !r lubridate::ymd("2022/07/04", tz = "America/Sao_Paulo")
  week: "Week 4"
  slug: 'Week%204'
  rpubs: 'https://rpubs.com/AndersonUyekita/part-2_course-project_statistical-inference'
  project_repo: 'https://github.com/AndersonUyekita/statistical-inference_course-project/tree/main/Part%202'
  codebook: 'https://github.com/AndersonUyekita/statistical-inference_course-project/blob/master/codebook.md'
  instructions: 'https://github.com/AndersonUyekita/statistical-inference_course-project/blob/main/Part%202/instructions.md'
always_allow_html: true
---

```{r setup, include=FALSE,message=FALSE,warning=FALSE,cache=TRUE}
# Defining document chunks options
knitr::opts_chunk$set(echo = TRUE,cache=TRUE,message=FALSE,warning=FALSE)

# Loading required libraries
library(rmarkdown)
library(lubridate)
library(ggplot2)
```

`r if(!knitr::is_html_output()) {sprintf(fmt = "* &#x1f468;&#x1F3FB;&#x200d;&#x1f4bb; Author: %s", params$author)}`
`r sprintf(fmt = "* &#x1f4da; Specialization: [%s](%s){target='_blank' rel='noopener'}", params$specialization, params$specialization_url)`
`r sprintf(fmt = "* &#x1f4d6; Course: [%s](%s){target='_blank' rel='noopener'}", params$course, params$course_url)`
    `r sprintf(fmt = "* &#x1F9D1;&#x200d;&#x1F3EB; Instructor: %s", params$instructor)`
`r sprintf(fmt = "* &#x1F4C6; %s", params$week)`
    `r sprintf(fmt = "* &#x1F6A6; Start: %s", format(params$course_start, "%A, %d %B %Y"))`
    `r sprintf(fmt = "* &#x1F3C1; Finish: %s", format(params$course_finish, "%A, %d %B %Y"))`
`r if(!knitr::is_html_output()) {sprintf(fmt = "* &#x1F4C4; README: [README.md](%s)", "./README.md")}else{sprintf(fmt = "* &#x1F4C4; README: [README.md](%s){target='_blank' rel='noopener'}", params$project_repo)}`
`r if(!knitr::is_html_output()) {sprintf(fmt = "* &#x1F30E; Rpubs: [Interactive Document](%s)", params$rpubs)}else{sprintf(fmt = "* &#x1F4E6; Github Repository: [Static Document](%s){target='_blank' rel='noopener'}", params$project_repo)}`

------------------------------------------------------------------------

## Instructions

### 1. Introduction

The project consists of two parts:

* A simulation exercise.
* Basic inferential data analysis.

You will create a report to answer the questions. Given the nature of the series, ideally you'll use knitr to create the reports and convert to a pdf. (I will post a very simple introduction to knitr). However, feel free to use whatever software that you would like to create your pdf.

Each pdf report should be no more than 3 pages with 3 pages of supporting appendix material if needed (code, figures, etcetera).

### 2. Part 2: Basic Inferential Data Analysis Instructions

Now in the second portion of the project, we're going to analyze the ToothGrowth data in the R datasets package.

* Load the ToothGrowth data and perform some basic exploratory data analyses
* Provide a basic summary of the data.
* Use confidence intervals and/or hypothesis tests to compare tooth growth by supp and dose. (Only use the techniques from class, even if there's other approaches worth considering)
* State your conclusions and the assumptions needed for your conclusions.

### 3. Review Criteria

 * Did you show where the distribution is centered at and compare it to the theoretical center of the distribution?
 * Did you show how variable it is and compare it to the theoretical variance of the distribution?
 * Did you perform an exploratory data analysis of at least a single plot or table highlighting basic features of the data?
 * Did the student perform some relevant confidence intervals and/or tests?
 * Were the results of the tests and/or intervals interpreted in the context of the problem correctly?
 * Did the student describe the assumptions needed for their conclusions?